-- NOTE: Subscriptions table and email-based authentication have been deprecated
-- Users now register with firstName, lastName, and a temporary local email
-- No subscription confirmation or email verification is required
-- This migration file is kept for reference but all subscription logic has been removed
